/**
 * 留言板（群聊风格）中文文案表。
 *
 * 为什么不用主题的 i18n 系统：这套群聊留言板引入了 137 个新 key，走 i18n 就得改
 * src/i18n/i18nKey.ts 与 6 个 src/i18n/languages/*.ts —— 那是上游的高频改动区，
 * 每次合并上游都会冲突。本文件是新增文件，文案集中在此，改文案只动这一处。
 * 若日后要恢复多语言，把 GB_LANG.xxx 换回 i18n(I18nKey.xxx) 并补 i18n 词条即可。
 */
export const GB_LANG = {
	gbAdmin: "站长",
	gbAdminRole: "管理员",
	gbAnonymousVisitor: "匿名访客",
	gbAuthExpired: "登录状态已失效，请重新登录",
	gbBackToBottom: "回到底部",
	gbCancelQuote: "取消引用",
	gbCharCount: "{count}/{max}",
	gbCloseAnnouncement: "关闭公告",
	gbCloseDeleteConfirm: "关闭删除确认",
	gbCloseGuestProfile: "关闭游客资料",
	gbCloseMembers: "关闭留言人列表",
	gbCloseTip: "关闭提示",
	gbComposerAria: "留言内容",
	gbComposerReplyTo: "回复 @{nick}",
	gbConnecting: "正在连接留言服务",
	gbCopied: "已复制",
	gbCopyFailed: "复制失败，请检查浏览器剪贴板权限",
	gbCopyMessage: "复制消息",
	gbCurrentUser: "当前用户：{name}",
	gbCurrentUserAria: "当前登录用户：{name}",
	gbDeleteFailed: "消息删除失败，请稍后重试",
	gbDeleteMessage: "删除消息",
	gbDeleteWarning: "删除后无法恢复，Waline 服务端也会同步删除这条消息。",
	gbEditFailed: "消息修改失败，请稍后重试",
	gbEditGuestProfile: "修改游客资料",
	gbEditMessage: "编辑消息",
	gbEditMessageWithName: "编辑 {nick} 的消息",
	gbEmail: "邮箱",
	gbEmailInvalid: "邮箱格式不正确",
	gbEmailPlaceholder: "用于头像，不公开",
	gbEmailTooltip: "邮箱：{value}",
	gbEmojiAria: "选择表情",
	gbEmojiImageTitle: "表情",
	gbEmojiLoadFailed: "Waline 表情加载失败，请稍后重试",
	gbEmojiPacksAria: "表情包",
	gbEmptyBody: "发送第一条消息，开启这段对话。",
	gbEmptyTitle: "还没有人发言",
	gbFillGuestProfile: "填写游客资料",
	gbGuestAccess: "游客访问",
	gbGuestProfile: "游客资料",
	gbGuestProfileAriaEmpty: "游客资料未填写",
	gbGuestProfileAriaFilled: "游客资料，昵称 {nick}，邮箱 {mail}，网址 {link}",
	gbGuestProfileNotFilled: "尚未填写游客资料",
	gbGuestProfileRequired: "请选择游客访问并填写资料，或登录后发送",
	gbGuestProfileRequiredDisabled: "请先通过游客访问填写资料后再发送",
	gbHiddenUntilVisible: "页面恢复可见后将自动加载留言板",
	gbImageTooLarge: "图片不能超过 5 MB",
	gbImageTooLargeInline: "Waline 原生图片不能超过 128 KB",
	gbImageTypeUnsupported: "仅支持 PNG、JPEG、GIF 或 WebP 图片",
	gbImageUploadFailed: "图片上传失败，请稍后重试",
	gbInsertEmojiAria: "插入 {key}",
	gbJumpToQuoteAria: "跳转到 {nick} 的原消息",
	gbJumpToQuoteTitle: "跳转到原消息",
	gbLink: "网址",
	gbLinkInvalid: "网站地址格式不正确",
	gbLinkProtocolInvalid: "网站地址仅支持 http 或 https",
	gbLinkTooltip: "网址：{value}",
	gbLoadFailedTitle: "留言板加载失败",
	gbLoadOlder: "加载更早消息",
	gbLoadingAria: "正在加载留言",
	gbLoadingEmoji: "加载表情",
	gbLoadingOlder: "正在加载历史消息",
	gbLoggedIn: "已登录",
	gbLoggingIn: "登录中",
	gbLoginExpired: "登录信息已失效，请重新登录",
	gbLoginFailed: "登录失败，请稍后重试",
	gbLoginInvalidResponse: "登录返回信息无效，请重新登录",
	gbLoginRequired: "请先登录后再发送消息",
	gbLoginVerifyFailed: "登录信息验证失败，请重新登录",
	gbLogoutWalineTitle: "退出 Waline 登录",
	gbMemberCountAria: "{count} 人",
	gbMembers: "留言人",
	gbMembersListAria: "留言人列表",
	gbMessageActionsAria: "消息操作",
	gbMessageCount: "{count} 条留言",
	gbMsgMaxLength: "消息不能超过 {max} 个字符",
	gbMsgMinLength: "消息至少需要 {min} 个字符",
	gbMsgReplyMarker: "消息内容不能以系统引用标记开头",
	gbNetworkDisconnected: "网络已断开，恢复连接后将自动同步",
	gbNewMessagesAria: "{count} 条新消息，回到最新消息",
	gbNickname: "昵称",
	gbNicknameMinLength: "游客昵称至少需要 {min} 个字符",
	gbNicknamePlaceholder: "至少 2 个字符",
	gbNicknameTooltip: "昵称：{value}",
	gbNoMoreMessages: "已经到最早一条消息",
	gbNotFilled: "未填写",
	gbOffline: "当前处于离线状态",
	gbOfflineInitial: "当前处于离线状态，恢复网络后将自动加载",
	gbOptional: "可选",
	gbPendingReview: "审核中",
	gbPlaceholder: "说点什么...",
	gbPlaceholderRequireLogin: "登录后参与留言",
	gbQuoteNotLoaded: "原消息暂未加载",
	gbQuoteReply: "引用回复",
	gbRefreshAria: "刷新留言板",
	gbRefreshNowAria: "立即刷新消息",
	gbRefreshNowTitle: "立即刷新",
	gbRefreshingAria: "留言板正在刷新",
	gbReload: "重新加载",
	gbRemoveImageAria: "移除待发送图片",
	gbRemoveImageTitle: "移除图片",
	gbReplyAria: "回复 {nick}",
	gbResizeAria: "调整输入框高度",
	gbResizeTitle: "向上拖动扩大输入框",
	gbRetrySync: "重试同步",
	gbSaveProfile: "保存资料",
	gbSendFailed: "消息发送失败",
	gbServerNotConfigured: "Waline 服务地址未配置",
	gbServerNotConfiguredLogin: "Waline 服务地址未配置，暂时无法登录",
	gbSyncFailed: "同步失败",
	gbSyncIntervalSuffix: "· 30 s",
	gbSyncOffline: "离线",
	gbSyncSyncing: "同步中",
	gbSyncWaiting: "等待同步",
	gbSyncedAt: "同步于 {time}",
	gbTitle: "留言板",
	gbToday: "今天",
	gbUploadImageAria: "上传图片",
	gbVisitSiteTitle: "访问 {nick} 的网站",
	gbVisitor: "访客",
	gbWalineEmojiAria: "Waline 表情",
	gbYesterday: "昨天",
	announcement: "公告",
	cancel: "取消",
	deleteLabel: "删除",
	deleting: "删除中",
	emoji: "表情",
	gotIt: "我知道了",
	image: "图片",
	login: "登录",
	logout: "退出",
	none: "无",
	retry: "重试",
	save: "保存",
	saving: "保存中",
	send: "发送",
	sending: "发送中",
} as const;
